management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8080


spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_storage}
    username: postgres
    password: postgres

  liquibase:
    change-log: db/changelog/db.changelog-main.yml
    enabled: true

  application:
    name: user-storage

service:
  stats:
    hit:
      url: ${STATS_SERVER_URL:http://localhost:9090/hit}

logging:
  level:
    org.springframework.web: TRACE

opentracing:
  jaeger:
    udp-sender:
      host: ${JAEGER_TRACE_HOST:localhost}
      port: 6831
    log-spans: true
    service-name: statistics

