CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255)                            NOT NULL,
    email   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);



CREATE TABLE IF NOT EXISTS events
(
    event_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation  VARCHAR(1024)                           NOT NULL,
    description VARCHAR(1024)                           NOT NULL,
    created     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    event_date  TIMESTAMP                               NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    title       VARCHAR(255)                            NOT NULL,
    views       BIGINT                                  NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (event_id)
);
